"""
tools_manager.py: Catalog of free tools that can be included on the Tools partition
"""

import logging
import os
import subprocess
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

logger = logging.getLogger("drivekit.tools")


@dataclass
class Tool:
    name: str
    description: str
    category: str
    install_method: str   # "brew", "url", "app_copy", "script"
    source: str           # brew formula, URL, or local path
    size_mb: int = 0
    url: str = ""
    selected: bool = False

    @property
    def display(self) -> str:
        return f"{self.name} — {self.description}"


def get_tool_catalog() -> list[Tool]:
    """Return the full catalog of available free tools."""
    return [
        # Security
        Tool("LuLu", "Free macOS firewall", "Security",
             "url", "https://github.com/objective-see/LuLu/releases/latest",
             15, "https://github.com/objective-see/LuLu"),
        Tool("KnockKnock", "Scan for persistent malware", "Security",
             "url", "https://github.com/objective-see/KnockKnock/releases/latest",
             10, "https://github.com/objective-see/KnockKnock"),
        Tool("BlockBlock", "Monitor persistence locations", "Security",
             "url", "https://github.com/objective-see/BlockBlock/releases/latest",
             8, "https://github.com/objective-see/BlockBlock"),

        # Diagnostics
        Tool("smartmontools", "S.M.A.R.T. disk health (smartctl)", "Diagnostics",
             "brew", "smartmontools", 5),
        Tool("Stats", "Menu bar system monitor", "Diagnostics",
             "brew", "stats", 12,
             "https://github.com/exelban/stats"),
        Tool("Trippy", "Network traceroute + ping", "Diagnostics",
             "brew", "trippy", 8,
             "https://github.com/fujiapple852/trippy"),

        # Data Recovery
        Tool("TestDisk", "Partition and file recovery", "Data Recovery",
             "brew", "testdisk", 3),
        Tool("PhotoRec", "File carving / recovery (included with TestDisk)", "Data Recovery",
             "brew", "testdisk", 0),

        # Maintenance
        Tool("Pearcleaner", "App uninstaller and cleaner", "Maintenance",
             "brew", "pearcleaner", 15,
             "https://github.com/alienator88/Pearcleaner"),
        Tool("mac-cleanup-py", "System cleanup scripts", "Maintenance",
             "brew", "mac-cleanup-py", 2),

        # Utilities
        Tool("dockutil", "Dock management CLI", "Utilities",
             "brew", "dockutil", 1),
        Tool("tccutil", "TCC permissions management", "Utilities",
             "brew", "tccutil", 1),

        # Deployment
        Tool("MDS", "Mac Deploy Stick (if installed)", "Deployment",
             "app_copy", "/Applications/MDS.app", 50),
        Tool("OCLP", "OpenCore Legacy Patcher (if installed)", "Deployment",
             "app_copy", "/Applications/OpenCore-Patcher.app", 80),
    ]


def copy_app_to_volume(app_path: str, tools_volume: str) -> bool:
    """Copy a .app bundle to the tools volume."""
    src = Path(app_path)
    if not src.exists():
        logger.warning(f"App not found: {app_path}")
        return False

    dest = Path(tools_volume) / "Apps" / src.name
    dest.parent.mkdir(parents=True, exist_ok=True)

    try:
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(str(src), str(dest))
        logger.info(f"Copied {src.name} to {dest}")
        return True
    except Exception as e:
        logger.error(f"Failed to copy {src.name}: {e}")
        return False


def download_brew_to_volume(formula: str, tools_volume: str) -> bool:
    """Download a brew formula's files and stage them on the tools volume."""
    dest = Path(tools_volume) / "Homebrew"
    dest.mkdir(parents=True, exist_ok=True)

    # Save a script that will install brew tools when run on a target Mac
    script = dest / "install_tools.sh"
    existing = script.read_text() if script.exists() else "#!/bin/bash\n# Auto-generated by Macktechs DriveKit\n\n"

    if formula not in existing:
        with open(script, "a") as f:
            if not existing.strip():
                f.write("#!/bin/bash\n# Auto-generated by Macktechs DriveKit\n\n")
                f.write("# Install Homebrew if not present\n")
                f.write('if ! command -v brew &>/dev/null; then\n')
                f.write('  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"\n')
                f.write("fi\n\n")
            f.write(f"brew install {formula}\n")
        os.chmod(script, 0o755)
    return True


def copy_scripts_to_volume(tools_volume: str) -> None:
    """Copy common repair scripts to the tools volume."""
    scripts_dir = Path(tools_volume) / "Scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)

    scripts = {
        "system_report.sh": """#!/bin/bash
# Macktechs System Report Generator
echo "========================================="
echo "  Macktechs System Report"
echo "  $(date)"
echo "========================================="
echo ""
echo "--- Hardware ---"
system_profiler SPHardwareDataType
echo ""
echo "--- Storage ---"
diskutil list
echo ""
echo "--- Battery ---"
system_profiler SPPowerDataType 2>/dev/null | head -20
echo ""
echo "--- SMART Status ---"
diskutil info disk0 | grep "SMART"
echo ""
echo "--- Network ---"
ifconfig en0 | grep "inet "
echo ""
echo "--- macOS Version ---"
sw_vers
""",
        "flush_caches.sh": """#!/bin/bash
# Flush DNS and system caches
sudo dscacheutil -flushcache
sudo killall -HUP mDNSResponder
echo "DNS cache flushed"
""",
        "reset_launch_services.sh": """#!/bin/bash
# Rebuild Launch Services database
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user
echo "Launch Services database rebuilt"
""",
        "check_malware_locations.sh": """#!/bin/bash
# Quick scan of common malware persistence locations
echo "Checking common malware locations..."
echo ""
echo "--- LaunchAgents (User) ---"
ls ~/Library/LaunchAgents/ 2>/dev/null
echo ""
echo "--- LaunchAgents (System) ---"
ls /Library/LaunchAgents/ 2>/dev/null
echo ""
echo "--- LaunchDaemons ---"
ls /Library/LaunchDaemons/ 2>/dev/null
echo ""
echo "--- Browser Extensions ---"
ls ~/Library/Application\\ Support/Google/Chrome/Default/Extensions/ 2>/dev/null | head -10
echo ""
echo "--- Login Items ---"
osascript -e 'tell application "System Events" to get the name of every login item' 2>/dev/null
""",
    }

    for name, content in scripts.items():
        path = scripts_dir / name
        path.write_text(content)
        os.chmod(path, 0o755)

    logger.info(f"Copied {len(scripts)} scripts to {scripts_dir}")
